import {VERSION,sources,causes,clock,duration} from './clinical.mjs';
export async function exportPDF(state,events){
 const {PDFDocument,StandardFonts,rgb}=window.PDFLib;
 const doc=await PDFDocument.create();doc.setTitle('Resus Record - '+(state.run['Run name / number']||'Run'));doc.setSubject('Unified resuscitation record');doc.setCreator('Resus Record '+VERSION);
 const regular=await doc.embedFont(StandardFonts.Helvetica),bold=await doc.embedFont(StandardFonts.HelveticaBold);const W=595.28,H=841.89,M=44,line=14,ink=rgb(.09,.2,.24),muted=rgb(.35,.43,.47);let page,y,pages=[];
 const clean=s=>String(s??'').replace(/[\u0000-\u0008\u000b\u000c\u000e-\u001f]/g,'').replace(/[–—]/g,'-').replace(/≥/g,'>=').replace(/≤/g,'<=').replace(/↻/g,'').replace(/’/g,"'");
 const canvas=document.createElement('canvas'),ctx=canvas.getContext('2d');
 function width(s,font,size){try{return font.widthOfTextAtSize(s,size);}catch{ctx.font=`${font===bold?'bold ':''}${size}px Arial`;return ctx.measureText(s).width;}}
 function newPage(){page=doc.addPage([W,H]);pages.push(page);y=H-M;page.drawText('RESUS RECORD',{x:M,y:y-12,size:11,font:bold,color:ink});page.drawText('SESSION EXPORT',{x:W-155,y:y-12,size:9,font:regular,color:muted});y-=40;}
 function room(h=25){if(y-h<48)newPage();}
 async function draw(s,x,size,font,color){try{font.encodeText(s);page.drawText(s,{x,y,size,font,color});}catch{const scale=3;ctx.font=`${font===bold?'bold ':''}${size*scale}px Arial`;canvas.width=Math.ceil(Math.max(1,ctx.measureText(s).width))+8;canvas.height=size*scale*1.8;ctx.font=`${font===bold?'bold ':''}${size*scale}px Arial`;ctx.fillStyle='#17323b';ctx.textBaseline='alphabetic';ctx.fillText(s,0,size*scale*1.2);const img=await doc.embedPng(canvas.toDataURL('image/png'));page.drawImage(img,{x,y:y-size*.6,width:canvas.width/scale,height:canvas.height/scale});}}
 async function text(value,{size=10,font=regular,color=ink,indent=0,gap=4}={}){const paragraphs=clean(value).split('\n');for(const p of paragraphs){let buf='';const parts=p.split(/(\s+)/);for(let word of parts){if(width(word,font,size)>W-2*M-indent){for(const ch of word){if(width(buf+ch,font,size)>W-2*M-indent){room(line);await draw(buf,M+indent,size,font,color);y-=line;buf='';}buf+=ch;}continue;}if(width(buf+word,font,size)>W-2*M-indent){room(line);await draw(buf.trimEnd(),M+indent,size,font,color);y-=line;buf=word.trimStart();}else buf+=word;}room(line);await draw(buf,M+indent,size,font,color);y-=line;}y-=gap;}
 async function heading(s){room(105);y-=10;await text(s,{size:15,font:bold,gap:10});}
 function teamColor(hex){if(!/^#[0-9a-f]{6}$/i.test(hex||''))return muted;return rgb(parseInt(hex.slice(1,3),16)/255,parseInt(hex.slice(3,5),16)/255,parseInt(hex.slice(5,7),16)/255);}
 async function dataRows(data){for(const[k,v]of Object.entries(data)){if(['Team member ID','Team color'].includes(k))continue;if(v!==''&&v!==null&&v!==undefined){if(k==='Performed by'){room(25);page.drawCircle({x:M+3,y:y+3,size:3.5,color:teamColor(data['Team color'])});}await text(`${k}: ${v}`,{indent:k==='Performed by'?14:9});}}}
 const stamp=t=>new Date(t).toLocaleString('en-GB',{hour12:false})+' ('+Intl.DateTimeFormat().resolvedOptions().timeZone+')';
 newPage();await text(state.run['Run name / number']||'Unnamed run',{size:23,font:bold,gap:10});await text('Unified resuscitation and peri-arrest record',{size:12,color:muted});await text(`Exported: ${stamp(Date.now())}`);await text(`Run opened: ${stamp(state.start)} | ${state.end?'Closed: '+stamp(state.end):'In progress at export'}`);await text(`Run duration at export: ${duration((state.end||Date.now())-state.start)} | Effective events: ${events.length} | Audit entries: ${state.events.length}`);await text('Testing build - independent clinical validation pending. This PDF is the only retained run record; app data is not saved.',{color:muted});
 await heading('Run context');await dataRows(state.run);await text('Blank fields were not entered. Explicit Unknown, Not measured and Not applicable values are preserved. Times use the device clock unless otherwise documented.',{color:muted});
 await heading('Team - names and colors');if(!state.team?.length)await text('No team members entered. Unassigned events have no selected performer.');for(const m of state.team||[]){room(25);page.drawCircle({x:M+3,y:y+3,size:4,color:teamColor(m.color)});await text(`${m.name}${m.role?' | '+m.role:''}${m.inactive?' | Removed from active team':''}`,{indent:14});}await text('Each event retains its performer name and color as recorded; later roster edits do not rewrite earlier attribution.',{color:muted});
 await heading('Reversible cause status');for(const c of causes){const e=events.filter(e=>e.type==='Reversible cause'&&e.data.Cause===c[1]).at(-1);await text(`${c[0]} - ${c[1]}: ${e?.data.Status||'Not assessed'}`,{font:bold});if(e)await dataRows(Object.fromEntries(Object.entries(e.data).filter(([k])=>k!=='Cause'&&k!=='Status')));}
 await heading('Medication administration totals');const med=events.filter(e=>e.type==='Medication'&&e.data.Status==='Administered');if(!med.length)await text('No administered medication recorded.');const incomplete=med.filter(e=>e.data.Delivery==='Not entered'||(e.data.Delivery==='Bolus'&&(!(Number(e.data['Actual dose / rate'])>0)||e.data['Dose units']==='Not entered')));if(incomplete.length)await text(`${incomplete.length} administration(s) have incomplete dose / delivery details and are excluded from totals. Totals below are partial.`,{font:bold});const totals={};for(const e of med){if(e.data.Delivery!=='Bolus'||!(Number(e.data['Actual dose / rate'])>0)||e.data['Dose units']==='Not entered')continue;const name=e.data.Drug==='Other'?e.data['Other drug / fluid']:e.data.Drug;const key=`${name} | ${e.data.Context} | ${e.data['Dose units']}`;if(!totals[key])totals[key]={count:0,total:0};totals[key].count++;totals[key].total+=Number(e.data['Actual dose / rate']||0);}for(const[k,v]of Object.entries(totals))await text(`${k}: ${Number(v.total.toFixed(4))} total; ${v.count} administered bolus(es).`);await text('Different units are kept separate. Infusion rates and changes appear in the timeline; rate sums are not administered totals.',{color:muted});
 await heading('Clinical timeline - effective entries');for(const e of events.filter(e=>e.type!=='Debrief')){room(55);await text(`${stamp(e.t)} | ${e.type}${e.correction?' [AMENDED]':''}`,{font:bold,gap:7});await text(`Recorded: ${stamp(e.entered)}${e.mode?' | '+e.mode:''}${e.weight?' | Weight snapshot '+e.weight+' kg ('+e.weightBasis+')':''}`,{size:8,color:muted});await dataRows(e.data);y-=7;}
 const review=events.filter(e=>e.type==='Debrief');await heading('Quality review - separate from clinical facts');if(!review.length)await text('No debrief recorded.');for(const e of review){await text(stamp(e.t),{font:bold});await dataRows(e.data);}
 const amendments=state.events.filter(e=>e.type==='Correction');await heading('Amendment audit trail');if(!amendments.length)await text('No corrections or voided entries.');for(const c of amendments){const orig=state.events.find(e=>e.id===c.target);await text(`${stamp(c.entered)} | ${c.voided?'VOID':'AMENDMENT'} | ${orig?.type||c.target}`,{font:bold});await dataRows(c.data);await text('Original event time: '+stamp(orig.t));await text('Original recorded fields:',{font:bold});await dataRows(orig.data);if(!c.voided){await text('Corrected event time: '+stamp(c.correctedTime));await text('Replacement fields:',{font:bold});await dataRows(c.replacement);}y-=10;}
 await heading('Reference version');await text(VERSION);for(const[n,url]of sources){await text(n,{font:bold});await text(url,{size:8,color:muted});}
 for(let i=0;i<pages.length;i++){const p=pages[i];p.drawText(`RESUS RECORD | ${state.end?'Closed run':'In progress snapshot'} | ${i+1} / ${pages.length}`,{x:M,y:26,size:8,font:regular,color:muted});}
 return doc.save();
}
