import {validWeight,fmt} from './clinical.mjs';

// Reference calculations only. Indication, route and administration remain explicit.
// SNHD takes precedence; supplemental Drug Cards entries are identified separately.
const snhdURL='https://media.southernnevadahealthdistrict.org/download/ems/ems-protocol-manual.pdf';
const S=page=>({source:`SNHD · July 2026 · p. ${page}`,url:`${snhdURL}#page=${String(page).split(',')[0].trim()}`});
const C=page=>({source:`Drug Cards · January 2026 · PDF p. ${page} · supplemental`,supplemental:true});
const R=(label,amount,unit,routes,source,extra={})=>({label,amount,unit,routes:routes.split('|'),...source,...extra});
const W=(label,factor,cap,unit,routes,source,extra={})=>R(label,null,unit,routes,source,{factor,cap,...extra});
const M=(label,note,source={})=>({label,note,manual:true,routes:[],...source});
const both=rows=>({Adult:rows,Pediatric:rows});
const IV='IV|IO',PAIN='Intranasal|IM|IV|IO',SED='Intranasal|IM|IV|IO';
export const medicationCatalog=[
 {name:'Acetaminophen (Tylenol/Ofirmev)',Adult:[R('Pain · IV / IO',1000,'mg',IV,S(47)),R('Pain · oral',[325,1000],'mg','Oral',S(47))],Pediatric:[W('Pain · IV / IO',15,1000,'mg',IV,S(101),{note:'Over 2 min.'}),M('Pain · oral','Use the age ≥3 months oral dosing chart; do not substitute the IV calculation.',S(102))]},
 {name:'Adenosine (Adenocard)',Adult:[R('Regular SVT · first dose',6,'mg',IV,S(65)),R('Regular SVT · second dose',12,'mg',IV,S(65))],Pediatric:[W('Regular SVT · first dose',.1,6,'mg',IV,S(115)),W('Regular SVT · second dose',.2,12,'mg',IV,S(115))],note:'Rapid push with flush. Wide-complex use only when regular and monomorphic.'},
 {name:'Albuterol',Adult:[R('Bronchospasm',[2.5,10],'mg','Nebulized',S(51))],Pediatric:[R('Bronchospasm · nonsevere',[2.5,5],'mg','Nebulized',S(107)),R('Bronchospasm · severe',[5,10],'mg','Nebulized',S(107))]},
 {name:'Amiodarone (Cordarone)',Adult:[R('Cardiac arrest · first dose',300,'mg',IV,S(27)),R('Cardiac arrest · second dose',150,'mg',IV,S(27)),R('Tachycardia with pulse',150,'mg',IV,S(65),{note:'In 50 mL NS over 10 min; physician order for the AF pathway.'})],Pediatric:[W('Cardiac arrest · first dose',5,300,'mg',IV,S(89),{note:'300 mg first-dose ceiling retained from the app’s AHA PALS reference.'}),W('Cardiac arrest · subsequent dose',5,150,'mg',IV,S(89),{note:'150 mg subsequent-dose ceiling retained from AHA PALS. Up to 3 total doses.'}),W('Tachycardia with pulse',5,null,'mg',IV,S(115),{note:'In 50 mL NS over 20 min; consult the treating clinician.'})]},
 {name:'Aspirin / Acetylsalicylic acid',Adult:[R('Suspected ACS',324,'mg','Oral',S(29))],Pediatric:[M('Pediatric use','No routine pediatric ACS dose in these references.')]},
 {name:'Atropine',Adult:[R('Bradycardia',1,'mg',IV,S(23),{note:'Every 3–5 min; maximum total 3 mg.'}),R('Organophosphate poisoning',2,'mg',IV,S(45),{note:'Every 15 min as needed for secretions / ventilatory resistance.'})],Pediatric:[W('Bradycardia',.02,.5,'mg',IV,S(85),{min:.1,note:'May repeat once after 5 min.'}),W('Organophosphate poisoning',.02,null,'mg',IV,S(99),{min:.1,note:'Every 15 min as needed; bradycardia ceiling does not apply.'})]},
 {name:'Bronchodilator MDI',...both([M('Bronchospasm','Assist with the patient’s prescribed inhaler dose.',S(51))])},
 {name:'Calcium chloride 10%',Adult:[R('Hyperkalemia / calcium-channel blocker poisoning',1000,'mg',IV,S('37, 45'),{note:'Slow administration.',concentration:100})],Pediatric:[W('Calcium-channel blocker poisoning',20,null,'mg',IV,S(99),{note:'Slow administration.',concentration:100})]},
 {name:'Dextrose 10% (D10W)',Adult:[R('Hypoglycemia',250,'mL',IV,S(19),{note:'D10: 25 g in 250 mL. May repeat once after 5 min.'})],Pediatric:[W('Hypoglycemia',5,250,'mL',IV,S(80),{note:'D10: 0.1 g/mL; maximum 25 g.'})]},
 {name:'Diazepam (Valium)',Adult:[R('Seizure',5,'mg','IM|IV|IO',S(55)),R('Post-intubation sedation',5,'mg',IV,S(69),{note:'Repeat after 5 min requires physician order.'})],Pediatric:[W('Seizure',.1,5,'mg','IM|IV|IO|Rectal',S(109)),W('Post-intubation sedation · IV / IO',.2,5,'mg',IV,S(119),{note:'Repeat after 5 min requires physician order.'}),W('Post-intubation sedation · rectal',.5,20,'mg','Rectal',S(119))]},
 {name:'Diltiazem (Cardizem)',Adult:[W('AF rate control · first dose',.25,null,'mg','IV',C(14),{note:'Over 2 min. Avoid preexcitation, hypotension, AV block and ventricular tachycardia.'}),W('AF rate control · repeat',.35,null,'mg','IV',C(14),{note:'After 15 min if indicated.'})],Pediatric:[M('Pediatric use','Not recommended by the supplied Drug Cards.',C(14))]},
 {name:'Diphenhydramine (Benadryl)',Adult:[R('Allergic reaction',50,'mg','IM|IV|IO|Oral',S(17)),R('Dystonic reaction',50,'mg','IM|IV|IO',S(45))],Pediatric:[W('Allergic reaction',1,50,'mg','IM|IV|IO|Oral',S(78)),W('Dystonic reaction',1,50,'mg','IM|IV|IO',S(99))]},
 {name:'Droperidol (Inapsine)',Adult:[R('Nausea / vomiting',1.25,'mg','IM|IV|IO',S(15)),R('Behavioral emergency · IV / IO',[2.5,5],'mg',IV,S(21)),R('Behavioral emergency · IM',5,'mg','IM',S(21)),R('Severe agitation · IM',[5,10],'mg','IM',S(21),{note:'Use the severe-agitation pathway; assess IMC-RASS and monitoring.'})],Pediatric:[W('Behavioral emergency · age >6 and <12 years',.2,5,'mg','IV|IM',S(82),{note:'Persistent risk, IMC-RASS +3 / +4 after nonpharmacologic measures.'})]},
 {name:'DuoNeb (albuterol + ipratropium)',...both([R('Bronchospasm',3,'mL','Nebulized',S('51, 107'))])},
 {name:'Epinephrine 1 mg/mL',Adult:[R('Anaphylaxis',.5,'mg','IM',S(17),{concentration:1,note:'Repeat every 15 min to total 1.5 mg.'}),R('Asthma in extremis',.5,'mg','IM',S(51),{concentration:1})],Pediatric:[W('Anaphylaxis',.01,.5,'mg','IM',S(78),{concentration:1,note:'Repeat every 5 min to total 1.5 mg.'}),W('Bronchospasm in extremis',.01,.5,'mg','IM',S(107),{concentration:1}),R('Stridor / croup',[3,5],'mg','Nebulized',S(105),{concentration:1})]},
 {name:'Epinephrine 0.1 mg/mL',Adult:[R('Cardiac arrest',1,'mg',IV,S(27),{concentration:.1,note:'Every 3–5 min.'})],Pediatric:[W('Cardiac arrest',.01,1,'mg',IV,S(89),{concentration:.1,note:'Every 3–5 min. 1 mg ceiling retained from AHA PALS.'}),W('Bradycardia',.01,1,'mg',IV,S(85),{concentration:.1,note:'Every 3–5 min; respiratory support and CPR when indicated.'})]},
 {name:'Epinephrine 10 mcg/mL (push-dose)',Adult:[R('Shock / bradycardia',10,'micrograms',IV,S('23, 59'),{concentration:10,note:'Every 2–5 min to protocol targets.'})],Pediatric:[W('Shock',.1,5,'micrograms',IV,S(111),{concentration:10,note:'Titrate to age-appropriate blood pressure.'})]},
 {name:'Etomidate (Amidate)',Adult:[W('Intubation induction',.3,30,'mg',IV,S(69)),W('Cardioversion sedation',.15,null,'mg',IV,S(65))],Pediatric:[W('Intubation induction',.3,20,'mg',IV,S(119)),W('Cardioversion sedation',.15,null,'mg',IV,S(115))]},
 {name:'Fentanyl',Adult:[W('Pain / post-intubation analgesia',1,100,'micrograms',PAIN,S('47, 69'),{note:'Pain: repeat after 10 min; further doses / another controlled substance require Medical Control.'})],Pediatric:[W('Pain / post-intubation analgesia',1,100,'micrograms',PAIN,S('101, 119'),{note:'Additional pain doses require physician order.'})]},
 {name:'Furosemide (Lasix)',Adult:[R('Pulmonary edema / CHF',[20,80],'mg','IV',C(25),{note:'Slow administration; assess volume status.'})],Pediatric:[W('Pulmonary edema / CHF',1,null,'mg','IV',C(25))]},
 {name:'Glucagon',Adult:[R('Hypoglycemia · no IV access',1,'mg','IM',S(19)),R('Beta-blocker poisoning',1,'mg','IM|IV|IO',S(45),{note:'May repeat once in 3–5 min.'})],Pediatric:[R('Hypoglycemia · weight <20 kg',.5,'mg','IM',S(80),{below:20}),R('Hypoglycemia · weight >20 kg',1,'mg','IM',S(80),{above:20}),M('Hypoglycemia · exactly 20 kg','The source leaves this boundary unspecified; confirm the prescribed dose.',S(80)),R('Beta-blocker poisoning',.5,'mg','IM|IV|IO',S(99),{note:'May repeat once in 3–5 min.'})]},
 {name:'Haloperidol (Haldol)',Adult:[R('Agitation · IV',5,'mg','IV',C(27),{note:'IV is off-label; continuous ECG monitoring.'}),R('Agitation · IM',10,'mg','IM',C(27))],Pediatric:[R('Agitation · ages 6–12 years',[1,3],'mg','IM',C(27),{weightCap:.15,note:'Maximum 0.15 mg/kg; age must be confirmed.'})]},
 {name:'Hydromorphone (Dilaudid)',Adult:[W('Pain',.01,1,'mg','IM|IV|IO',S(47),{note:'May repeat after 10 min; further doses require Medical Control.'})],Pediatric:[M('Pediatric use','No hydromorphone regimen in the current SNHD pediatric pain protocol.',S(101))]},
 {name:'Hydroxocobalamin (Cyanokit)',Adult:[R('Suspected cyanide poisoning',5,'g',IV,S(45),{note:'Over 15 min.'})],Pediatric:[M('Suspected cyanide poisoning','Use the pediatric Cyanokit chart in the source; preparation and dose require confirmation.',S(114))]},
 {name:'Ipratropium (Atrovent)',Adult:[R('Bronchospasm',[.5,1.5],'mg','Nebulized',S(51))],Pediatric:[R('Bronchospasm · nonsevere',.5,'mg','Nebulized',S(107)),R('Bronchospasm · severe',[1,1.5],'mg','Nebulized',S(107))]},
 {name:'Ketamine (Ketalar)',Adult:[W('Pain',.2,null,'mg',PAIN,S(47),{note:'No repeat. Not for chest pain / suspected ACS / STEMI.'}),W('Intubation induction · IV / IO',2,null,'mg',IV,S(69)),W('Intubation induction · IM',4,null,'mg','IM',S(69)),W('Behavioral emergency',[3,4],400,'mg','IM',S(21),{note:'Maximum total 400 mg.'})],Pediatric:[W('Intubation induction · IV / IO',2,200,'mg',IV,S(119)),W('Intubation induction · IM',4,400,'mg','IM',S(119)),W('Behavioral emergency · age >6 and <12 years',4,400,'mg','IM',S(82),{note:'Persistent risk, IMC-RASS +3 / +4 after nonpharmacologic measures.'})]},
 {name:'Labetalol',Adult:[R('Severe hypertension · first dose',20,'mg','IV',C(31),{note:'Over 2 min; confirm HR >60.'}),R('Severe hypertension · second dose',40,'mg','IV',C(31)),R('Severe hypertension · subsequent dose',80,'mg','IV',C(31),{note:'Repeat interval 10 min; maximum total 300 mg.'})],Pediatric:[M('Pediatric use','No prehospital pediatric regimen recommended by the supplied Drug Cards.',C(31))]},
 {name:'Levalbuterol (Xopenex)',Adult:[R('Bronchospasm',[1.25,5],'mg','Nebulized',S(51))],Pediatric:[R('Bronchospasm · nonsevere',[1.25,2.5],'mg','Nebulized',S(107)),R('Bronchospasm · severe',[2.5,5],'mg','Nebulized',S(107))]},
 {name:'Lidocaine',...both([W('Cardiac arrest · first dose',1,null,'mg',IV,S('27, 89')),W('Cardiac arrest · repeat',.5,null,'mg',IV,S('27, 89'),{note:'One repeat if refractory, per SNHD.'})])},
 {name:'Lidocaine, IO analgesia',Adult:[R('Conscious IO analgesia',40,'mg','IO',C(32),{note:'Slow administration; verify the local IO protocol and concentration.'})],Pediatric:[W('Conscious IO analgesia',.5,null,'mg','IO',C(32),{note:'Verify the local IO protocol and preparation. No concentration inferred from the card.'})]},
 {name:'Lidocaine 2% lubricant',Adult:[M('Nasal intubation preparation','Topical 2% lubricant; amount depends on preparation and procedure.',S(145))],Pediatric:[M('Pediatric use','SNHD advises against pediatric nasotracheal intubation.',S(145))]},
 {name:'Lorazepam (Ativan)',Adult:[W('Seizure',.1,4,'mg',IV,C(35),{note:'May repeat once after 10–15 min; maximum 8 mg in 12 h.'}),R('Sedation · IV / IO',2,'mg',IV,C(35)),R('Sedation · IM',4,'mg','IM',C(35))],Pediatric:[W('Seizure',.1,4,'mg',IV,C(35)),W('Sedation · IV / IO',.05,2,'mg',IV,C(35)),W('Sedation · IM',.05,4,'mg','IM',C(35))]},
 {name:'Magnesium sulfate',Adult:[R('Torsades / severe asthma',2,'g',IV,S('51, 65'),{note:'In 50 mL NS over 10 min.'}),R('Pre-eclampsia',4,'g',IV,S(41),{note:'In 50 mL NS over 20 min.'}),R('Eclampsia · IV / IO',5,'g',IV,S(41),{note:'In 50 mL NS over 5 min.'}),R('Eclampsia · IM',8,'g','IM',S(41),{note:'4 g in each buttock.'})],Pediatric:[W('Torsades',25,null,'mg',IV,S(115),{note:'In 50 mL NS over 10 min.'}),W('Severe bronchospasm',50,2000,'mg',IV,S(107),{note:'In 50 mL NS over 10 min.'})]},
 {name:'Metoclopramide (Reglan)',Adult:[R('Nausea / vomiting',10,'mg','IV|IM',S(15),{note:'IV over 1–2 min.'})],Pediatric:[R('Nausea / vomiting · age ≥8 years',5,'mg','IV|IO|IM',S(76),{note:'IV / IO over 1–2 min; confirm age.'})]},
 {name:'Methylprednisolone (Solu-Medrol)',Adult:[W('Bronchospastic disease / adrenal insufficiency',2,125,'mg','IV',C(37))],Pediatric:[W('Bronchospastic disease / adrenal insufficiency',2,null,'mg','IV',C(37),{note:'Pediatric ceiling not supplied by this card; confirm the selected protocol.'})]},
 {name:'Midazolam (Versed)',Adult:[W('Seizure · initial',.1,5,'mg',SED,S(55)),W('Seizure · repeat',.05,2.5,'mg',SED,S(55),{note:'Further dosing requires physician order.'}),W('Intubation induction / post-intubation sedation',.1,10,'mg',SED,S(69)),W('Post-intubation sedation · repeat',.05,2.5,'mg',SED,S(69),{note:'Once after 5 min; further doses require physician order.'}),R('Behavioral emergency',[2.5,5],'mg',SED,S(21))],Pediatric:[W('Seizure / intubation induction · initial',.1,5,'mg',SED,S('109, 119')),W('Seizure / post-intubation sedation · repeat',.05,2.5,'mg',SED,S('109, 119')),W('Post-intubation sedation · initial',.1,10,'mg',SED,S(119))]},
 {name:'Morphine',Adult:[W('Pain',.1,10,'mg','IM|IV|IO',S(47),{note:'May repeat after 10 min; further doses require Medical Control.'})],Pediatric:[W('Pain',.1,10,'mg','IM|IV|IO',S(101),{note:'Additional doses require Medical Control.'})]},
 {name:'Naloxone (Narcan)',Adult:[R('Opioid respiratory depression · titrated',[.4,2],'mg',PAIN,S(45)),R('Opioid respiratory depression · nasal product',[2,4],'mg','Intranasal',S(45))],Pediatric:[W('Opioid respiratory depression · titrated',.1,null,'mg',PAIN,S(99),{note:'Titrate to respiratory effort; maximum cumulative 10 mg. Confirm product and dose.'}),R('Opioid respiratory depression · nasal product',[2,4],'mg','Intranasal',S(99))]},
 {name:'Nitroglycerin',Adult:[R('ACS / pulmonary edema',.4,'mg','Sublingual',S('29, 49'),{note:'Check blood pressure, HR and contraindications; repeat interval 5 min per pathway.'}),R('Pulmonary edema · DBP >100 mm Hg',1.6,'mg','Sublingual',S(49),{note:'Repeat every 5 min only while DBP remains >100.'})],Pediatric:[M('Pediatric use','No routine pediatric regimen in the selected sources.')]},
 {name:'Norepinephrine (Levophed)',Adult:[W('Shock · titrated infusion',[.05,.5],null,'micrograms/min',IV,C(42),{factorUnit:'micrograms/kg/min',delivery:'Infusion start',note:'Range is a reference, not an automatically selected starting rate.'})],Pediatric:[W('Shock · initial infusion',.05,null,'micrograms/min',IV,C(42),{factorUnit:'micrograms/kg/min',delivery:'Infusion start',note:'Titrate per order; card lists a maximum of 2 micrograms/kg/min.'})]},
 {name:'Ondansetron (Zofran)',Adult:[R('Nausea / vomiting',4,'mg','Oral|IM|IV|IO',S(15),{note:'Oral route is ODT.'})],Pediatric:[W('Nausea / vomiting · injectable',.15,4,'mg','IM|IV|IO',S(76)),M('Nausea / vomiting · ODT','0.15 mg/kg, maximum 4 mg; round up to the nearest half tablet after confirming tablet strength.',S(76))]},
 {name:'Oral glucose',...both([M('Hypoglycemia','Patient must protect their airway. Use the product / protocol dose; weight alone does not determine it.',S('19, 80'))])},
 {name:'Oxymetazoline (Afrin)',...both([R('Epistaxis · each nostril',2,'sprays','Intranasal',S('33, 93'),{note:'Dose shown is per nostril; follow with direct pressure.'})])},
 {name:'Phenylephrine, nasal',...both([R('Epistaxis · each nostril',2,'sprays','Intranasal',S('33, 93'),{note:'Dose shown is per nostril; follow with direct pressure.'})])},
 {name:'Phenylephrine, push-dose',Adult:[R('Shock',[100,200],'micrograms',IV,S(59),{concentration:100,note:'Every 2–5 min to maintain SBP >90.'})],Pediatric:[M('Pediatric use','Confirm a pediatric vasopressor protocol; the SNHD pediatric shock pathway specifies epinephrine.',S(111))]},
 {name:'Prochlorperazine (Compazine)',Adult:[M('Nausea / vomiting','Up to 10 mg IV / IM / IO; select the ordered dose.',S(15))],Pediatric:[M('Pediatric use','No regimen in the SNHD pediatric nausea protocol.',S(76))]},
 {name:'Rocuronium',Adult:[W('Intubation',[.6,1.2],null,'mg',IV,C(47)),W('Maintenance paralysis',[.1,.2],null,'mg',IV,C(47),{note:'Card interval 12 min. Paralysis does not provide sedation / analgesia.'})],Pediatric:[W('Intubation · age >3 months',[.9,1.2],null,'mg',IV,C(47),{note:'Off-label pediatric use; confirm age, airway plan and sedation.'})]},
 {name:'Sodium bicarbonate',Adult:[R('Selected poisoning / hyperkalemia',50,'mEq',IV,S('37, 45'),{note:'Not routine undifferentiated arrest therapy.'})],Pediatric:[W('Sodium-channel blocker poisoning · wide QRS',1,50,'mEq',IV,S(99),{note:'May repeat once in 3–5 min if QRS remains wide.'})]},
 {name:'Solu-Cortef / Hydrocortisone',...both([M('Adrenal insufficiency','Use the patient’s prescribed dose; no universal weight-only dose in this pathway.',S('59, 111'))])},
 {name:'Succinylcholine',Adult:[W('Intubation · IV / IO',[1,1.5],150,'mg',IV,C(49)),W('Intubation · IM',[3,4],150,'mg','IM',C(49))],Pediatric:[W('Intubation · infant / small child',2,null,'mg',IV,C(49),{note:'Confirm developmental group; age is not inferred from weight.'}),W('Intubation · older child / adolescent',1,null,'mg',IV,C(49)),W('Intubation · IM',[3,4],150,'mg','IM',C(49))],note:'Confirm contraindications including hyperkalemia risk and malignant hyperthermia; paralysis is not sedation.'},
 {name:'Terbutaline',Adult:[R('Bronchospasm',.25,'mg','Subcutaneous',C(50),{note:'May repeat every 20 min twice.'})],Pediatric:[M('Pediatric use','No prehospital pediatric regimen recommended by the supplied Drug Cards.',C(50))]},
 {name:'Tranexamic acid (TXA)',Adult:[R('Postpartum hemorrhage',1,'g',IV,S(39),{note:'Over 10 min; only within 3 h after delivery.'}),R('Traumatic hemorrhage',1,'g','IV',C(51),{note:'Over 10 min; within 3 h of injury. Confirm the local trauma pathway.'})],Pediatric:[W('Hemorrhage',20,null,'mg','IV',C(51),{note:'Over 10 min. Pediatric maximum not supplied by this card; confirm the selected protocol.'})]},
 {name:'Vecuronium',...both([M('Neuromuscular blockade','No dosing entry in the supplied Drug Cards or SNHD formulary. Enter the treating clinician’s selected dose.')])}
].sort((a,b)=>a.name.localeCompare(b.name));

export const medicationOptions=medicationCatalog.map(m=>m.name);
export function medicationReferences(name,mode,weight,basis){
 const med=medicationCatalog.find(m=>m.name===name);
 if(!med||!['Adult','Pediatric'].includes(mode))return [];
 const known=validWeight(weight)&&['Measured','Estimated'].includes(basis),w=known?Number(weight):null;
 return med[mode].filter(r=>!(r.label==='Hypoglycemia · exactly 20 kg'&&known&&w!==20)).map((r,index)=>{
  const weighted=r.factor!==undefined||r.weightCap!==undefined||r.below!==undefined||r.above!==undefined;
  const result={...r,index,name,mode,weight:known?w:null,basis,weighted,note:[med.note,r.note].filter(Boolean).join(' ')};
  if(r.manual)return {...result,display:'Confirm dose',values:[]};
  if(weighted&&!known)return {...result,disabled:true,display:'Weight and basis needed',values:[]};
  if((r.below!==undefined&&w>=r.below)||(r.above!==undefined&&w<=r.above))return {...result,disabled:true,display:'Outside this weight group',values:[]};
  const inputs=Array.isArray(r.factor??r.amount)?(r.factor??r.amount):[r.factor??r.amount];
  const cap=r.weightCap!==undefined?w*r.weightCap:r.cap??Infinity;
  // Do not fabricate a dose if an age/weight-limited range has no overlap.
  if(r.weightCap!==undefined&&inputs[0]>cap)return {...result,disabled:true,display:'Confirm dose for this age / weight',values:[]};
  const values=[...new Set(inputs.map(n=>Number(Math.max(r.min??0,Math.min(r.factor!==undefined?n*w:n,cap)).toFixed(6))))];
  const formula=r.factor!==undefined?`${inputs.map(fmt).join('–')} ${r.factorUnit||r.unit+'/kg'}${r.cap?`; max ${fmt(r.cap)} ${r.unit}`:''}${r.min?`; min ${fmt(r.min)} ${r.unit}`:''}`:r.weightCap!==undefined?`Maximum ${r.weightCap} mg/kg`:'Fixed dose';
  return {...result,values,formula,display:`${values.map(fmt).join('–')} ${r.unit}`,volume:r.concentration?`${values.map(n=>fmt(n/r.concentration)).join('–')} mL`:null};
 });
}
